title: Crypto Voice
description: Terms of Service & Privacy Policy

# Tema seçimi
theme: jekyll-theme-cayman

# GitHub butonlarını gizle
github:
  is_project_page: false
show_downloads: false

# Özel CSS
kramdown:
  syntax_highlighter_opts:
    disable: true

# Sayfa stili
style: >-
  <style>
    .page-header { 
      background: #000001 !important; 
      background-image: none !important;
    }
    .main-content { 
      background: #000001 !important; 
      color: #FFFFFF !important;
    }
    .main-content h1, 
    .main-content h2, 
    .main-content h3 { 
      color: #FDDC43 !important; 
    }
    body { 
      background: #000001 !important; 
      color: #FFFFFF !important;
    }
    a { 
      color: #FDDC43 !important; 
    }
  </style>
