remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Crypto Voice
description: Terms of Service & Privacy Policy

# GitHub butonlarını gizle
github:
  is_project_page: false
show_downloads: false

# Tema renkleri ve stili
colors:
  header-bg-color: "#159957"
  header-bg-color-secondary: "#155799"
  section-headings-color: "#159957"
  body-text-color: "#606c71"
  body-link-color: "#1e6bb8"

# Özel CSS
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sayfa stili
style: |
  .main-content h1, .main-content h2, .main-content h3, .main-content h4, .main-content h5, .main-content h6 { 
    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto; 
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: normal;
    color: #159957;
  }
  .main-content p {
    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto;
    font-size: 16px;
    line-height: 1.5;
  }
  .page-header {
    padding: 2rem 1rem;
  }
  a {
    color: #1e6bb8;
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
