# Site ayarları
title: Crypto Voice
description: Terms of Service & Privacy Policy

# GitHub Pages ayarları
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub butonlarını gizle
github:
  is_project_page: false
show_downloads: false

# Özel CSS
style: >-
  <style>
    body { background-color: #000001 !important; color: #FFFFFF !important; }
    .container-lg { background-color: #000001 !important; }
    .markdown-body { background-color: #000001 !important; color: #FFFFFF !important; }
    .markdown-body h1, 
    .markdown-body h2, 
    .markdown-body h3, 
    .markdown-body h4, 
    .markdown-body h5, 
    .markdown-body h6 { color: #FDDC43 !important; }
    a { color: #FDDC43 !important; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
