# Site ayarları
title: Crypto Voice
description: Legal Documents

# Tema ayarı
theme: jekyll-theme-cayman

# GitHub butonlarını gizle
github:
  is_project_page: false
show_downloads: false

# Özel CSS
style: >-
  <style>
    /* Ana stil */
    body {
      background-color: #000001;
      color: #FFFFFF;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }

    /* Header bölümü */
    .page-header {
      background-color: #000001;
      background-image: none;
      padding: 2rem 1rem;
      color: #FFFFFF;
    }

    /* İçerik bölümü */
    .main-content {
      background-color: #000001;
      color: #FFFFFF;
    }

    /* Başlıklar */
    .main-content h1,
    .main-content h2,
    .main-content h3,
    .main-content h4,
    .main-content h5,
    .main-content h6 {
      color: #FDDC43;
      font-weight: 600;
    }

    /* Linkler */
    a {
      color: #FDDC43;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
      color: #FDDC43;
    }

    /* Liste maddeleri */
    .main-content ul,
    .main-content ol {
      color: #FFFFFF;
    }

    /* Paragraflar */
    .main-content p {
      color: #FFFFFF;
      line-height: 1.6;
    }
  </style>
