remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Crypto Voice
description: Terms of Service & Privacy Policy

# GitHub butonlarını gizle
github:
  is_project_page: false
show_downloads: false

# Tema özelleştirmeleri
theme: jekyll-theme-cayman

# Sayfa stili
style: |
  :root {
    --header-bg-color: #000001;
    --header-bg-color-secondary: #000001;
    --section-headings-color: #FDDC43;
  }
  .page-header {
    background-color: #000001 !important;
    background-image: none !important;
    padding: 2rem 1rem;
  }
  body {
    background-color: #000001 !important;
    color: #FFFFFF !important;
  }
  .main-content {
    background-color: #000001 !important;
    color: #FFFFFF !important;
  }
  .main-content h1, 
  .main-content h2, 
  .main-content h3, 
  .main-content h4, 
  .main-content h5, 
  .main-content h6 { 
    color: #FDDC43 !important;
  }
  a {
    color: #FDDC43 !important;
  }
  a:hover {
    color: #FDDC43 !important;
    text-decoration: underline;
  }
